import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dark, neobrutalism } from '@clerk/themes'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  
} from '@clerk/nextjs'
import Sidebar from "@/components/sidebar/sidebar";
import Topbar from "@/components/dashboard/Topbar";



const inter = Inter({ subsets: ["latin"] });;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: dark,
      signIn: { baseTheme: neobrutalism },
    }}>
      <html lang="en">
        
         <body
          className={`${inter.className} text-stone-950 bg-stone-100`}      >
          <SignedOut>
          
          <SignInButton  class="fixed top-0 left-0 w-screen h-screen flex  
                items-center justify-center ">Click here to Sign In </ SignInButton  >
            
          
              
          </SignedOut> 
          <SignedIn> 
             <div className="grid gap-4 p-4 grid-cols-[220px,_1fr]"  >
              <Sidebar />
              
              <div  className="bg-white rounded-lg pb-4 shadow h" >
              <Topbar />
                {children}
              
              </div>
            </div> 
           
           
              
          </SignedIn>
         </body>
        
      </html>
    </ClerkProvider>
  );
}
